# Generated by Django 4.2 on 2024-12-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('preferred_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('progress', 'On Progress')], default='progress', max_length=10, null=True)),
            ],
        ),
    ]
