# Generated by Django 4.2 on 2024-12-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('categories', models.CharField(blank=True, choices=[('to-do', 'To-Do'), ('task', 'Task'), ('shop', 'Shop')], max_length=10, null=True)),
                ('list_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('progress', 'On Progress')], default='progress', max_length=10, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('private', models.BooleanField(blank=True, default=False, null=True)),
                ('private_pass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListPictures',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(height_field='image_height', upload_to='list/media', width_field='image_width')),
                ('list_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='list.listpictures'),
        ),
    ]
